{{- if .Values.secrets.enabled }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Chart.Name }}-secrets
  namespace: {{ .Values.namespace.name }}
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "{{ .Values.secrets.objectName }}"
        objectType: "secretsmanager"
{{- end }}