# Production values
namespace:
  create: true
  name: country-chicken

replicaCount: 3

image:
  repository: nexus.company.com/docker/country-chicken-backend
  tag: "1.0.0"
  pullPolicy: Always

serviceAccount:
  create: true
  name: country-chicken-prod-sa
  irsaRoleArn: arn:aws:iam::123456789012:role/country-chicken-irsa

resources:
  requests:
    cpu: "500m"
    memory: "1Gi"
  limits:
    cpu: "1"
    memory: "2Gi"

autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 60

config:
  SPRING_PROFILES_ACTIVE: prod
  JAVA_TOOL_OPTIONS: "-XX:MaxRAMPercentage=75.0"

ingress:
  enabled: true
  className: nginx
  host: backend.countrychicken.com
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"

secrets:
  enabled: true
  objectName: "country-chicken/prod/db"